### ISSUE TITLE
how can i install boost c++ library

### ISSUE THREAD

**Issue by SPARKtechBD** [JamesBremner/TERN#2]
I have downloaded and unzipped but how can i install it in my windows machine?

**Comment by JamesBremner** [comment]
You need to add the boost include folder to the compiler search path.

The method for this depends on which IDE you use.

It is very easy for code::blocks.  When you open the project, you will be prompted to enter the boost global variable.  Browse to the boost folder and enter - code:blocks will automatically find the include folder.

![image](https://cloud.githubusercontent.com/assets/2046227/25314466/5af659c8-2812-11e7-9178-7bef027092c7.png)

If your using a different IDE, then you will have to use whatever method is required by the IDE to add to the compiler search path.  If you unfamiliar with how to do this, then you should switch to using code::blocks.

**Comment by JamesBremner** [comment]
Hello?  I have not heard from you!  Did my answer help you solve this issue?  If so, please let me know and close this issue.
